[phases.setup]
aptPkgs = ["libglib2.0-0", "libxcb1", "libxcb-shm0", "libx11-6"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv", ". /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"